FROM node:20

WORKDIR /opt/server

COPY package*.json . 
COPY *.js .

RUN npm cache clean --force \
    && npm install

ENV REDIS_HOST="redis" \
    CATALOGUE_HOST="catalogue" \
    PORT=8080

EXPOSE 8080

CMD ["node", "server.js"]
